export enum Message {
  UPDATE_PLAYER,
  UPDATE_PLAYER_NAME,
  READY_TO_CONNECT,
  DISCONNECT_PRESENTATION,
  CONNECT_TO_COMPUTER,
  DISCONNECT_FROM_COMPUTER,
  STOP_SCREEN_SHARE,
  CONNECT_WHITEBOARD,
  DISCONNECT_WHITEBOARD,
  VIDEO_CONNECTED,
  ADD_MESSAGE,
  SEND_ROOM_DATA,
}
